### ISSUE TITLE
Possible over-instrumentation on the Mirror Screen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/geometric-optics-basics#16]
For #3 

On the Mirror screen in Basics, there are a few instances that seem like over-instrumenation. The features are non-existent or irrelevant, but they also don't do any harm. I don't intend to feature any of these elements, so they won't clutter up the tree for clients. I'll defer to @pixelzoom's judgment about whether or not these can or should be un-instrumented.

- [x] `mirrorScreen.view.controls.controlPanel.opticSubpanel.focalLengthControl` - not applicable to flat mirror
- [x] `mirrorScreen.view.controls.controlPanel.opticSubpanel.radiusOfCurvatureControl` - not applicable to flat mirror
- [ ] `mirrorScreen.view.controls.opticShapeRadioButtonGroup` - only contains one radio button
- [x] `mirrorScreen.view.visibleProperties.focalPointsVisibleProperty` - corresponding checkbox doesn't exist on this screen
- [x] `mirrorScreen.view.visibleProperties.twoFPointsVisibleProperty` - corresponding checkbox doesn't exist on this screen

**Comment by pixelzoom** [comment]
On hold until 1.1 prototype is published.  I don't want to introduce master changes that make it more difficult to cherry-pick.

**Comment by pixelzoom** [comment]
@arouinfar ready for review in master.   Deviations from your change requests:

* I did not change `mirrorScreen.view.controls.opticShapeRadioButtonGroup`.  We had previously decided that it was OK if the client made the single radio button visible.  And it didn't seem like it was worth the work involved.

* Additionally `mirrorScreen.view.visibleProperties.guidesVisibleProperty` is only instrumented for the Lens screen, since it's irrelevnt for mirrors.

**Comment by arouinfar** [comment]
Thanks @pixelzoom, looks good in master.
