### ISSUE TITLE
2F points still visible when checkbox is disabled by preference menu

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/geometric-optics-basics#35]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/858
If the 2F points are on and you remove the checkbox with the preferences setting, the points remain and can't be removed until you reenable the checkbox.
**Steps to reproduce**
1. Go to the Lens screen
2. Turn on 2F points
3. Go to the preferences menu and turn off the 2f checkbox

**Visuals**
![2fstillthere](https://user-images.githubusercontent.com/41024075/202819062-ddc3f903-0913-4b6e-9fec-4cc087ab25b8.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Geometric Optics: Basics‬
URL: https://phet-dev.colorado.edu/html/geometric-optics-basics/1.2.0-rc.1/phet/geometric-optics-basics_all_phet.html
Version: 1.2.0-rc.1 2022-11-18 16:30:43 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1536x714
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
I don't think this is a bug, it's the behavior that I expected.  The Preference is whether the checkbox is visibile; it's not whether the points are visible. And hiding the 2F Points checkbox shouldn't hide the 2F points, because a PhET-iO instructional designer may want to show the 2F points, but hide the checkbox to prevent the student from turning them off. 

@arouinfar do you agree? If so, please close this issue as "won't fix".  If not, please specify the desired behavior.

**Comment by arouinfar** [comment]
> @arouinfar do you agree? 

Yes, completely. Thanks @pixelzoom.

> If so, please close this issue as "won't fix". 

Will do!
