### ISSUE TITLE
Add info about second point feature to examples.md

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/geometric-optics-basics#40]
For https://github.com/phetsims/qa/issues/939:

In the examples document, the "Set the Object Position" and "Collect Data about the Object and Images" sections give examples for the `arrowObject2`, `lightObject2`, and `secondPoint` even though they are not visible by default in the Basics version. 

 @arouinfar via slack: 
>I think they should be in the examples, but I should maybe add information that the 2nd point feature should be enabled first.

**Comment by pixelzoom** [comment]
Rats… I just finished publishing 1.3.0-rc.3 for GO and GO:Basics, and creating QA issues https://github.com/phetsims/qa/issues/950 and https://github.com/phetsims/qa/issues/951.  Then I noticed that that this issue is still open. I didn't see it because I forgot to look in geometric-optics-basics. 

@arouinfar How do you want to proceed? My feeling is that we should fix in master, but defer to a future release, unless another RC is required. Otherwise the cost to change at this point is not justified.

**Comment by arouinfar** [comment]
> My feeling is that we should fix in master, but defer to a future release, unless another RC is required. Otherwise the cost to change at this point is not justified.

I completely agree @pixelzoom. The fix amounts to reordering the list of phetioIDs, which does not seem serious enough to require an additional RC test.

**Comment by pixelzoom** [comment]
Note to self: If there's another RC needed for the 1.3 release, cherry-pick https://github.com/phetsims/phet-io-sim-specific/commit/022371cebed79ff4edfad50b8c0d744951649884. Otherwise just close this issue, and the change will be picked up in a future 1.4 release.

**Comment by pixelzoom** [comment]
No additional reasons to do another RC cycle were identified, so closing this issue.  The improvement in https://github.com/phetsims/phet-io-sim-specific/commit/022371cebed79ff4edfad50b8c0d744951649884 will be picked up in a future 1.4 release.

Closing.
